[package]
name = "api_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.21"  # from rustls-platform-verifier-android, sync version
getter = { path = "../getter", default-features = false, features = ["native-tokio", "rustls-platform-verifier-android"] }
upgradeall-platform-adapter = { path = "../platform_adapter" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
