name: labeled issue to project

on:
  issues:
    types: [labeled]
jobs:
  labeled-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: labeled Todo issue to project
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        if: contains(github.event.issue.labels.*.name, 'Todo')
        with:
          action-token: '${{ secrets.GH_TOKEN }}'
          project-url: 'https://github.com/orgs/DUpdateSystem/projects/1'
          column-name: 'Android 端需求'
          label-name: 'Todo'

      - name: labeled Doing issue to project
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        if: contains(github.event.issue.labels.*.name, 'Doing')
        with:
          action-token: '${{ secrets.GH_TOKEN }}'
          project-url: 'https://github.com/orgs/DUpdateSystem/projects/1'
          column-name: '进行中'
          label-name: 'Doing'

      - name: labeled Solved issue to project
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        if: contains(github.event.issue.labels.*.name, 'Solved')
        with:
          action-token: '${{ secrets.GH_TOKEN }}'
          project-url: 'https://github.com/orgs/DUpdateSystem/projects/1'
          column-name: 'Android 已完成'
          label-name: 'Solved'

      - name: labeled bug issue to project
        uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        if: contains(github.event.issue.labels.*.name, 'bug')
        with:
          action-token: '${{ secrets.GH_TOKEN }}'
          project-url: 'https://github.com/orgs/DUpdateSystem/projects/1'
          column-name: 'BUG'
          label-name: 'bug'